[project]
name = "aws-cdk-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aws-cdk-lib>=2.238.0,<3.0.0",
    "constructs>=10.0.0,<11.0.0",
]
